image: node:6.9.4

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - npm install pm2@latest -g
            - pm2 deploy ecosystem.json production --force